<a href="https://colab.research.google.com/github/biffsocko/SUNY_Poly_NCS590/blob/main/lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#!/usr/bin/python3

Tom Murphy
NCS590 
Lab 3
Test save

In [20]:
import numpy as np
import pandas as pd

In [3]:
# To create 1-D array
#1- np.arange(start, end+1) #returns a 1-D numpy array object

print(np.arange(0,5))

print(np.arange(2,10))

[0 1 2 3 4]
[2 3 4 5 6 7 8 9]


In [4]:
# To create 1-D array
#2- np.array( [list] or (tuple) ) #returns a 1-D numpy array object

print(np.array([1,2,3,4])) # converts a list to Numpy array

print(np.array((1,2,3,4))) # converts a tuple to Numpy array

[1 2 3 4]
[1 2 3 4]


In [5]:
print(type([1,2,3,4]))

print(type(np.array([1,2,3,])))

print(type((1,2,3,4)))

print(type(np.array((1,2,3,4))))

<class 'list'>
<class 'numpy.ndarray'>
<class 'tuple'>
<class 'numpy.ndarray'>


In [6]:
# To create N-D array
#2- np.array( [list of lists] ) #returns an N-D numpy array object

print(np.array([[1,2,3], [4,5,6], [7,8,9]])) #convert to N-D array

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
# access one element
#array_name[row, column]
array2= np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(array2)

print(array2[0,0])
print(array2[1,0])
print(array2[2,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
5
11


In [9]:
# To display the shape of a numpy array

array1= np.array([1,2,3])
array2= np.array([[1,2], [4,5,], [7,8]])

print(array1.shape)
print(array2.shape)

(3,)
(3, 2)


In [15]:
# access range of elements
#array_name[start_row : end_row+1, start_column : end_column+1]
array2= np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(array2)

print(array2[0:1,0:1])
print("--------------------")
print(array2[0:2,0:1])
print("--------------------")
print(array2[0:2,0:3])
print("--------------------")
print(array2[0:3,0:4])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1]]
--------------------
[[1]
 [5]]
--------------------
[[1 2 3]
 [5 6 7]]
--------------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
 #sum the elements of an array

array2= np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(array2)
print("--------------------")

print(array2.sum())

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------------------
78


In [17]:
# sum the elements of each row
print(array2.sum(axis=1))

# sum the elements of each column
print(array2.sum(axis=0))

[10 26 42]
[15 18 21 24]


In [18]:
# calculate the max or min or mean of an array

array2= np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(array2)
print("--------------------")

print(array2.max())
print(array2.min())
print(array2.mean())

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------------------
12
1
6.5


In [21]:
#pd.series( [list] ) # returns a pandas series

array=np.array(['A', 'B', 'C'])
print (array)

print("--------------------")

series=pd.Series(['A', 'B', 'C'])
print (series)

['A' 'B' 'C']
--------------------
0    A
1    B
2    C
dtype: object


In [22]:
# display the shape of the seies
print(series.shape)

#return the series values
print(series.values)


(3,)
['A' 'B' 'C']


In [23]:
#return min or max or mean of a series values
series2=pd.Series([13,35,22])

print(series2.min())
print(series2.max())
print(series2.mean())

13
35
23.333333333333332


In [24]:
#index is not necessarily to be a number. It can be more than that.

print(series2)

print("----------------")

series3=pd.Series([13,35,22], index=["John", "Mike", "David"])
print(series3)

0    13
1    35
2    22
dtype: int64
----------------
John     13
Mike     35
David    22
dtype: int64


In [25]:
# pd.Dataframe( [list of lists], index=[list of row index], columns=[list of column index] ) # returns a pandas dataframe

array=np.array([[1,2,3], [4,5,6], [7,8,9]])
print(array)

print("-------------------")

dataframe=pd.DataFrame([[1,2,3], [4,5,6], [7,8,9]])
print(dataframe)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-------------------
   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [26]:
dataframe2=pd.DataFrame([[1,2,3], [4,5,6], [7,8,9]], index=["John", "Mike", "David"], columns=["quiz1", "quiz2", "quiz3"])
dataframe2

quiz1  quiz2  quiz3
John       1      2      3
Mike       4      5      6
David      7      8      9

In [27]:
# returns a numpy array of random values from normal distributions
# np.random.randn(#rows, #columns)

array=np.random.randn(4,2)

print(array)

[[-0.83912263 -1.33600295]
 [-0.74566165 -0.3176803 ]
 [-1.16009355  0.21382217]
 [-1.73905577  1.03163412]]


In [28]:
# returns a range of  dates
# pd. date_range(start date, end date, frequency)

date1=pd.date_range('2023-9-1','2023-9-3', freq='d')
print(date1)

print("------------------------------------------------------------------------------------")

date2=pd.date_range('2022-9-1','2023-9-3', freq='m')
print(date2)

DatetimeIndex(['2023-09-01', '2023-09-02', '2023-09-03'], dtype='datetime64[ns]', freq='D')
------------------------------------------------------------------------------------
DatetimeIndex(['2022-09-30', '2022-10-31', '2022-11-30', '2022-12-31',
               '2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30',
               '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31'],
              dtype='datetime64[ns]', freq='M')
